# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c16fbf79d3b63e9af728521b20c357583791d006ebcb23cad0c7a9651fdf676bc27b9bf499dfc0457bf94f348aab22304ce0bada9b34143892d9d0dbe3d742

test:
  secret_key_base: 1bab4569ad770dda0e543b3ab7b415a6b79ea919e554cdc4dd7811b4d83ccd5efd49f5f0c89af317bf0074f313d18d9895facfe094dc7eb6961af008d7ab1913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
